@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6">
                <h3>Inflation AT</h3>
                <p>
                    Der Durchschnitt der Inflation zwischen 1980 und 2020 lag bei 2,5 %
                </p>
            </div>
            <div class="col-6">
                <h3>Inflation DE</h3>
                <p>
                    Der Durchschnitt der Inflation zwischen 1980 und 2020 lag bei 2,6 %
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-6">
                <table class="table table-bordered table-dark">
                    <thead>
                        <tr>
                            <th>Monat</th>
                            <th>Inflation %</th>
                            <th>VPI *</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>2020</td>
                            <td>1,4</td>
                            <td>257,6</td>
                        </tr>
                        <tr>
                            <td>2019</td>
                            <td>1,5</td>
                            <td>254,1</td>
                        </tr>
                        <tr>
                            <td>2018</td>
                            <td>2,0</td>
                            <td>250,3</td>
                        </tr>
                        <tr>
                            <td>2017</td>
                            <td>2,1</td>
                            <td>245,4</td>
                        </tr>
                        <tr>
                            <td>2016</td>
                            <td>0,9</td>
                            <td>240,4</td>
                        </tr>
                        <tr>
                            <td>2015</td>
                            <td>0,9</td>
                            <td>238,2</td>
                        </tr>
                        <tr>
                            <td>2014</td>
                            <td>1,7</td>
                            <td>236,1</td>
                        </tr>
                        <tr>
                            <td>2013</td>
                            <td>2,0</td>
                            <td>232,1</td>
                        </tr>
                        <tr>
                            <td>2012</td>
                            <td>2,4</td>
                            <td>227,6</td>
                        </tr>
                        <tr>
                            <td>2011</td>
                            <td>3,3</td>
                            <td>222,2</td>
                        </tr>
                        <tr>
                            <td>2010</td>
                            <td>1,9</td>
                            <td>215,1</td>
                        </tr>
                        <tr>
                            <td>2009</td>
                            <td>0,5</td>
                            <td>211,1</td>
                        </tr>
                        <tr>
                            <td>2008</td>
                            <td>3,2</td>
                            <td>210,1</td>
                        </tr>
                        <tr>
                            <td>2007</td>
                            <td>2,2</td>
                            <td>203,6</td>
                        </tr>
                        <tr>
                            <td>2006</td>
                            <td>1,5</td>
                            <td>199,2</td>
                        </tr>
                        <tr>
                            <td>2005</td>
                            <td>2,3</td>
                            <td>196,2</td>
                        </tr>
                        <tr>
                            <td>2004</td>
                            <td>2,1</td>
                            <td>191,8</td>
                        </tr>
                        <tr>
                            <td>2003</td>
                            <td>1,3</td>
                            <td>187,9</td>
                        </tr>
                        <tr>
                            <td>2002</td>
                            <td>1,8</td>
                            <td>185,5</td>
                        </tr>
                        <tr>
                            <td>2001</td>
                            <td>2,7</td>
                            <td>182,2</td>
                        </tr>
                        <tr>
                            <td>2000</td>
                            <td>2,3</td>
                            <td>177,4</td>
                        </tr>
                        <tr>
                            <td>1999</td>
                            <td>0,6</td>
                            <td>173,4</td>
                        </tr>
                        <tr>
                            <td>1998</td>
                            <td>0,9</td>
                            <td>172,4</td>
                        </tr>
                        <tr>
                            <td>1997</td>
                            <td>1,3</td>
                            <td>170,8</td>
                        </tr>
                        <tr>
                            <td>1996</td>
                            <td>1,9</td>
                            <td>168,7</td>
                        </tr>
                        <tr>
                            <td>1995</td>
                            <td>2,2</td>
                            <td>165,5</td>
                        </tr>
                        <tr>
                            <td>1994</td>
                            <td>3,0</td>
                            <td>162,0</td>
                        </tr>
                        <tr>
                            <td>1993</td>
                            <td>3,6</td>
                            <td>157,2</td>
                        </tr>
                        <tr>
                            <td>1992</td>
                            <td>4,1</td>
                            <td>151,8</td>
                        </tr>
                        <tr>
                            <td>1991</td>
                            <td>3,3</td>
                            <td>145,8</td>
                        </tr>
                        <tr>
                            <td>1990</td>
                            <td>3,3</td>
                            <td>141,1</td>
                        </tr>
                        <tr>
                            <td>1989</td>
                            <td>2,5</td>
                            <td>136,6</td>
                        </tr>
                        <tr>
                            <td>1988</td>
                            <td>2,0</td>
                            <td>133,3</td>
                        </tr>
                        <tr>
                            <td>1987</td>
                            <td>1,4</td>
                            <td>130,7</td>
                        </tr>
                        <tr>
                            <td>1986</td>
                            <td>1,7</td>
                            <td>128,9</td>
                        </tr>
                        <tr>
                            <td>1985</td>
                            <td>3,2</td>
                            <td>126,7</td>
                        </tr>
                        <tr>
                            <td>1984</td>
                            <td>5,6</td>
                            <td>122,8</td>
                        </tr>
                        <tr>
                            <td>1983</td>
                            <td>3,3</td>
                            <td>116,3</td>
                        </tr>
                        <tr>
                            <td>1982</td>
                            <td>5,4</td>
                            <td>112,6</td>
                        </tr>
                        <tr>
                            <td>1981</td>
                            <td>6,8</td>
                            <td>106,8</td>
                        </tr>
                        <tr>
                            <td>1980</td>
                            <td>6,4</td>
                            <td>100,0</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-6">
                <table class="table table-bordered table-dark">
                    <thead>
                        <tr>
                            <th>Monat</th>
                            <th>Inflation %</th>
                            <th>VPI *</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>2020</td>
                            <td>0,5</td>
                            <td>105,8</td>
                        </tr>
                        <tr>
                            <td>2019</td>
                            <td>1,4</td>
                            <td>105,3</td>
                        </tr>
                        <tr>
                            <td>2018</td>
                            <td>1,8</td>
                            <td>103,8</td>
                        </tr>
                        <tr>
                            <td>2017</td>
                            <td>1,5</td>
                            <td>102,0</td>
                        </tr>
                        <tr>
                            <td>2016</td>
                            <td>0,5</td>
                            <td>100,5</td>
                        </tr>
                        <tr>
                            <td>2015</td>
                            <td>0,5</td>
                            <td>100,5</td>
                        </tr>
                        <tr>
                            <td>2014</td>
                            <td>1,0</td>
                            <td>99,5</td>
                        </tr>
                        <tr>
                            <td>2013</td>
                            <td>1,4</td>
                            <td>98,5</td>
                        </tr>
                        <tr>
                            <td>2012</td>
                            <td>2,0</td>
                            <td>97,1</td>
                        </tr>
                        <tr>
                            <td>2011</td>
                            <td>2,1</td>
                            <td>95,2</td>
                        </tr>
                        <tr>
                            <td>2010</td>
                            <td>1,1</td>
                            <td>93,2</td>
                        </tr>
                        <tr>
                            <td>2009</td>
                            <td>0,3</td>
                            <td>92,2</td>
                        </tr>
                        <tr>
                            <td>2008</td>
                            <td>2,6</td>
                            <td>91,9</td>
                        </tr>
                        <tr>
                            <td>2007</td>
                            <td>2,3</td>
                            <td>89,6</td>
                        </tr>
                        <tr>
                            <td>2006</td>
                            <td>1,6</td>
                            <td>87,6</td>
                        </tr>
                        <tr>
                            <td>2005</td>
                            <td>1,5</td>
                            <td>86,2</td>
                        </tr>
                        <tr>
                            <td>2004</td>
                            <td>1,7</td>
                            <td>87,9</td>
                        </tr>
                        <tr>
                            <td>2003</td>
                            <td>1,1</td>
                            <td>83,5</td>
                        </tr>
                        <tr>
                            <td>2002</td>
                            <td>1,3</td>
                            <td>82,6</td>
                        </tr>
                        <tr>
                            <td>2001</td>
                            <td>2,0</td>
                            <td>81,5</td>
                        </tr>
                        <tr>
                            <td>2000</td>
                            <td>1,4</td>
                            <td>79,9</td>
                        </tr>
                        <tr>
                            <td>1999</td>
                            <td>0,6</td>
                            <td>78,8</td>
                        </tr>
                        <tr>
                            <td>1998</td>
                            <td>0,9</td>
                            <td>78,3</td>
                        </tr>
                        <tr>
                            <td>1997</td>
                            <td>2,0</td>
                            <td>77,6</td>
                        </tr>
                        <tr>
                            <td>1996</td>
                            <td>1,3</td>
                            <td>76,1</td>
                        </tr>
                        <tr>
                            <td>1995</td>
                            <td>1,8</td>
                            <td>75,1</td>
                        </tr>
                        <tr>
                            <td>1994</td>
                            <td>2,6</td>
                            <td>73,8</td>
                        </tr>
                        <tr>
                            <td>1993</td>
                            <td>4,5</td>
                            <td>71,9</td>
                        </tr>
                        <tr>
                            <td>1992</td>
                            <td>5,0</td>
                            <td>68,8</td>
                        </tr>
                        <tr>
                            <td>1991</td>
                            <td>3,7</td>
                            <td>65,5</td>
                        </tr>
                        <tr>
                            <td>1990</td>
                            <td>2,6</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1989</td>
                            <td>2,8</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1988</td>
                            <td>1,2</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1987</td>
                            <td>0,2</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1986</td>
                            <td>-0,1</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1985</td>
                            <td>2,0</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1984</td>
                            <td>2,5</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1983</td>
                            <td>3,2</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1982</td>
                            <td>5,2</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1981</td>
                            <td>6,3</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>1980</td>
                            <td>5,4</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12">
                <p>VPI = Verbraucherpreisindex</p>
            </div>
        </div>
    </div>
@endsection
